#!/usr/bin/env bash

# use colorized output when listing files and don't show group
if [[ $OSTYPE =~ darwin ]]; then
  alias ls='ls -G';
  alias ll='ls -lG';
  alias la='ls -lGa';
else
  alias ls='ls --color=auto';
  alias ll='ls --color=auto -l';
  alias la='ls --color=auto -la';
fi;

# always ask for confirmation when removing files
alias rm='rm -i';

# always ask for confirmation when copying files
alias cp='cp -i';

# always colorise grep output
alias grep='grep --color=auto';

# make bash expand other aliasses for sudo, http://git.io/wtfbash
alias sudo='sudo ';

# git aliases
alias gl='git log --oneline --all --color --graph --decorate';

# always use vim instead of vi, this _strangly_ prevents unexplained non-zero exit codes on OS X
alias vi='vim';

alias ip='curl -X GET "https://httpbin.org/ip" -H "accept: application/json"';
alias week='date +%V';
alias epoch='date +%s';
