#!/usr/bin/env bash

git_completion_macos='/Library/Developer/CommandLineTools/usr/share/git-core/git-completion.bash';
git_completion_fedora='/usr/share/doc/git/contrib/completion/git-completion.bash';

if [[ -x ${git_completion_macos} ]]; then
  source "${git_completion_macos}";
fi;

if [[ -e ${git_completion_fedora} ]]; then
  source "${git_completion_fedora}";
fi;

unset git_completion_macos;
unset git_completion_fedora;
