#!/usr/bin/env bash

git_completion='/Library/Developer/CommandLineTools/usr/share/git-core/git-completion.bash';

if [[ -x ${git_completion} ]]; then
  source "${git_completion}";
fi;

unset git_completion
