#!/usr/bin/env bash
# vim: ft=sh

# 128 lines of history is enough
export HISTSIZE=128
export HISTFILESIZE=$HISTSIZE;
# don't log duplicate commands and blank commands
export HISTCONTROL=ignoreboth;
# list of commands that should not be added to history
export HISTIGNORE='ls:ll:la:exit:[bf]g';
# add date and time to history
export HISTTIMEFORMAT='%F %T '
# make `vi` the default system editor
export EDITOR='/usr/bin/vim';
export VISUAL='/usr/bin/vim';
# Don't keep `less` history
export LESSHISTFILE='-'
# Automatically pass options to `less`
# - do not clear the screen upon exit: -X
# - quit if the man page is less than one screen long: -F
# - make `less` more colorful: -R
export LESS='FXR'

if [[ $OSTYPE =~ darwin ]]; then
  export LSCOLORS=dxbxbEaEBxxEhEhBaDaCaD;
fi;

# Prefer English and use UTF-8.
printf -v available_locales ' %s ' "$(locale -a)";
for lang in en_GB en_US en; do
  for locale in "${lang}".{UTF-8,utf8}; do
    if [[ ${available_locales} =~ ${locale} ]]; then
      export LC_ALL="${locale}";
      export LANG="${lang}";
      break 2;
    fi;
  done;
done;
unset available_locales lang locale;
