#!/usr/bin/env bash

dot() {
  local DOT_FILES="${HOME}/.dotfiles";

  if [[ ${GIT_DIR} == ${DOT_FILES} ]]; then
    unset GIT_DIR;
  else
    if [[ ${PWD} == ${HOME} ]]; then
      export GIT_DIR=${DOT_FILES};
    else
      echo "You need to be in ${HOME}";
      return 1;
    fi
  fi
}

r() {
  cd "$(git root)"
}
