#!/usr/bin/env bash

dot() {
  if [[ ${GIT_DIR} == ${HOME}/.dotfiles ]]; then
    unset GIT_DIR;
  else
    [[ ${PWD} == ${HOME} ]] || return;
    export GIT_DIR="$HOME/.dotfiles";
  fi
}

r() {
  cd "$(git root)"
}
