#!/usr/bin/env bash

dot() {
  local DOT_FILES="${HOME}/.dotfiles";

  if [[ ${GIT_DIR} == ${DOT_FILES} ]]; then
    unset GIT_DIR;
  else
    [[ ${PWD} == ${HOME} ]] || return;
    export GIT_DIR=${DOT_FILES};
  fi
}

r() {
  cd "$(git root)"
}
