#!/usr/bin/env bash
# vim: ft=bash

export HISTSIZE=32768;
export HISTFILESIZE=$HISTSIZE;
# don't log duplicate commands and blank commands
export HISTCONTROL=ignoreboth;
# list of commands that should not be added to history
export HISTIGNORE='ls:ll:la:exit:[bf]g';
# make `vi` the default system editor
export EDITOR='/usr/bin/vim';
export VISUAL='/usr/bin/vim';
# Use `less` for paging when using `man`.
# - do not clear the screen upon exit: -X
# - quit if the man page is less than one screen long: -F
# - make less more colorful: -R
export PAGER='less -FXR';
# Don't keep less history
export LESSHISTFILE=-

# Prefer English and use UTF-8.
printf -v available_locales ' %s ' "$(locale -a)";
for lang in en_GB en_US en; do
  for locale in "${lang}".{UTF-8,utf8}; do
    if [[ ${available_locales} =~ ${locale} ]]; then
      export LC_ALL="${locale}";
      export LANG="${lang}";
      break 2;
    fi;
  done;
done;
unset available_locales lang locale;
