name: Git checks

on: pull_request

permissions:
  contents: read

jobs:
  no-fixups:
    runs-on: ubuntu-latest
    steps:
      - uses: matijs/no-fixups-action@183d9d2310ed1382144a873e83d03c0d20be55f1 #v1.1.2
