name: Git checks

on:
  pull_request:
    branches:
      - dotfiles

permissions:
  contents: read

jobs:
  no-fixups:
    runs-on: ubuntu-latest
    steps:
      - uses: matijs/no-fixups-action@8dfcf79304e29c3aa37e327cfc1d3685dca3c6c0 #v1.1.4
